### ISSUE TITLE
Unrecognized token

### ISSUE THREAD

**Issue by peoplemerge** [TaylorBriggs/stripe-lambda#1]
Hi Taylor - getting this

{"message": "Could not parse request body into json: Unrecognized token \'stripeToken\': was expecting (\'true\', \'false\' or \'null\')\n at [Source: [B@7ceaad5b; line: 1, column: 13]"}

**Comment by peoplemerge** [comment]
Ah figured out I had to configure the form from application/x-www-form-urlencoded using a mapping template to json.

**Comment by TaylorBriggs** [comment]
Cool, definitely let me know if you run into any other issues! This is one of my first tries at using Lambda functions on AWS so I'm sure there are a few things than can be improved upon.

**Comment by owntheweb-archive** [comment]
> Ah figured out I had to configure the form from application/x-www-form-urlencoded using a mapping template to json.

Hello @peoplemerge,
I'm working through this issue right now as well. Did you configure this edit in API Gateway? Thanks for the hint. I'll keep exploring while absorbing coffee.

**UPDATE:**
I think I found where to place the mapping template in API Gateway. Under the POST request, under "Integration Request", I can create a "application/x-www-form-urlencoded" mapping template. At the moment I'm starting with this, working through new errors (progress!) 

`{
"formparams" : $input.json('$')
}`

Not quite there yet, so open to thoughts as I continue. I'll be sure to post once I get it worked out.

**UPDATE:**
I'm having better luck with [this template](https://forums.aws.amazon.com/thread.jspa?messageID=673012&tstart=0#673012). I'm still getting errors, but it may be due to testing a form locally. 

> Ah figured out I had to configure the form from application/x-www-form-urlencoded using a mapping template to json.

Hello @peoplemerge,
I'm working through this issue right now as well. Did you configure this edit in API Gateway? Thanks for the hint. I'll keep exploring while absorbing coffee.

**UPDATE:**
I think I found where to place the mapping template in API Gateway. Under the POST request, under "Integration Request", I can create a "application/x-www-form-urlencoded" mapping template. At the moment I'm starting with this, working through new errors (progress!) 

`{
"formparams" : $input.json('$')
}`

Not quite there yet, so open to thoughts as I continue. I'll be sure to post once I get it worked out.

**UPDATE:**
I'm having better luck with [this template](https://forums.aws.amazon.com/thread.jspa?messageID=673012&tstart=0#673012). I'm still getting errors, but it may be due to testing a form locally. 

**UPDATE:**
While [this solution](https://forums.aws.amazon.com/thread.jspa?messageID=673012&tstart=0#673012) is helping me get variables sent to this stripe payment script, I'm learning that I may need to use something else first (another custom Lambda function maybe?) to handle token info prior to making a charge. Correct me if I'm off. Here's my little test page:

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Stripe Test Payment</title>
</head>
<body>

<h1>Stripe Test Payment</h1>

<p>This is only a test. DO NOT ENTER YOUR PERSONAL CREDIT CARD INFO.</p>

<form action="https://my-stripe-lambda-url" method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_mystripepublictestkey"
    data-amount="1000"
    data-name="Space Foundation"
    data-description="Express Donation"
    data-locale="auto"
    data-zip-code="true"
    data-image="img/stripe-icon.jpg"
    data-panel-label="Donate"
    >
  </script>
</form>

</body>
</html>
```

Here's the resulting event object getting sent to the script, resulting in errors (source needs to be the token, email under a different name, no amount being passed in):

```
{ 
  stripeToken: 'tok_mynewtokenhere',
  stripeTokenType: 'card',
  stripeEmail: 'myemail@somemail.com' 
}
```

I must be missing a step. Any thoughts? Thanks in advance as I work though this. :D

**Comment by peoplemerge** [comment]
@owntheweb yes I think you are on the right track.  I'm looking through my API gateway setup / lambda function and have summarized it below.  

* The HTML form
I have roughly the same contents as you have, posting to my action.  Expect this must be served over HTTPS, don't bother even testing over an insecure page.

* API Gateway
Yes - the edit I was referring to is indeed in the API Gateway.  Yes, this tool is a real puzzler. 

I have a POST method Execution
Client -> Method Request
 Auth:None, ARN (my account)

Integration Request
Type: Lambda function
Request Body Passthrough - When no template matches the request Content-Type
Content-Type - application/x-www-form-urlencoded

Integration Response 
HTTP status .*
Output passthrough Yes

Method Response 200
No model

* Lambda function

You need just one custom lambda function.  

I started with the basic function... that AWS starter provides
```
exports.handler = (event, context) => {
    // TODO implement
};
```

Then I prepended the following environment to bring in the stripe dependency:

```
require('dotenv').load();
var stripe = require('stripe')(process.env.STRIPE_SECRET_KEY);
```

Then in the handler function, I dropped the following method call: https://stripe.com/docs/api/node#create_charge.  That stripe method is sufficient for my use case.

In particular I needed the amount, stripeToken, currency, description, and (nullable) stripeEmail.  Note description and stripeEmail I had to pass through decodeURIComponent().

Configuration - I see existing role lambda_basic_execution.  I think I was prompted to create this at the time I created the lambda function.  I think I kept it just for console debugging.

Mine has:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents"
      ],
      "Resource": "arn:aws:logs:*:*:*"
    }
  ]
}
```

**Comment by owntheweb-archive** [comment]
@peoplemerge Wow! Thank you for the wonderful feedback! This is very helpful. In an attempt to make it worth your effort, I'll share an alternative method I managed to work through today. 

Using jQuery's ajax methods, I was able to bypass another server-side script for one-time donations . Since the purchase request is submitted in application/json format, it also bypasses need for conversion templates in Gateway API. I started from a clean API with a POST method, [CORS does need to be setup](http://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html) for the POST method (creates an OPTIONS method with extra config) to prevent access errors there.

Disclaimer: I'm not sure if this is "kosher" yet with the token coming back to the client then getting bounced to the API/lambda function. Reading up now...

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Express Donation</title>
<link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Express Donation Test</h1>

      <div id="formSpace">
        <p>This is only a test. <b>DO NOT ENTER YOUR PERSONAL CREDIT CARD INFO.</b></p>

        <hr>

        <form class="form-horizontal">

          <div class="form-group">
            <label for="creditName" class="col-sm-4 control-label">Name Credited To Donation</label>
            <div class="col-sm-8">
              <input type="text" class="form-control" placeholder="e.g. Joe Smith or ABC Company or In memory of Joe Smith" id="creditName" name="creditName">
            </div>
          </div>

          <div class="form-group">
            <label for="creditName" class="col-sm-4 control-label">Donation Amount (dollars)</label>
            <div class="col-sm-4">
              <div class="input-group">
                <div class="input-group-addon">$</div>
                <input type="number" class="form-control" id="amount" name="amount" placeholder="Amount" value="10">
                <div class="input-group-addon">.00</div>
              </div>
            </div>
          </div>

          <div class="form-group">
            <label for="creditName" class="col-sm-4 control-label">Email for Receipt</label>
            <div class="col-sm-8">
              <input type="email" class="form-control" placeholder="Your Email" id="emailAddress" name="emailAddress">
            </div>
          </div>

          <div class="form-group">
            <label for="creditName" class="col-sm-4 control-label">Thank You for Your Support!</label>
            <div class="col-sm-8">
              <a class="btn btn-primary" href="javascript:;" role="button" id="donateBtn">Donate!</a>
            </div>
          </div>

          <hr>

        </form>
      </div>

    </div>
  </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="bootstrap/js/bootstrap.min.js"></script>
<script src="https://checkout.stripe.com/checkout.js"></script>

<script>
$(function() {
  var amt = 0;
  var email;
  var creditName;

  var stripeHandler = StripeCheckout.configure({
    key: 'pk_test_public_stripe_key',
    image: 'img/stripe-icon.jpg',
    locale: 'auto',
    token: function(token) {
      $('#formSpace').html('Finalizing transaction...');

      var data = {
        source: token.id,
        amount: amt,
        description: 'Space Foundation: Express Donation',
        zip: token.card.address_zip,
        zipCheck: token.card.address_zip_check,
        cvcCheck: token.card.cvc_check,
        creditName: creditName,
        receipt_email: email
      };

      var request = $.ajax({
        url: "https://thegatewayapiurl.amazonaws.com/prod/donate",
        method: "POST",
        dataType: 'json',
        contentType: 'application/json; charset=utf-8',
        data: JSON.stringify(data)
      });

      request.done(function(results) {
        if(results.status === "succeeded" && results.success === true) {
          $('#formSpace').html('Success!');
        } else {
          //look up docs on other status
          $('#formSpace').html('Hmmmm... Something went wrong. Try again?');
          console.log(results);
        }
      });
       
      request.fail(function(jqXHR, textStatus) {
        console.log("Request failed: " + textStatus);
        $('#formSpace').html('Oops! The request failed. Try again?');
      });
    }
  });

  $('#donateBtn').click(function() {
    amt = $('input[name=amount]').val() * 100;
    email = $('input[name=emailAddress]').val();
    //finalize purchase using token
    creditName = $('input[name=creditName]').val();
    if(creditName == '') {
      creditName = 'Anonymous Donor'
    }

    stripeHandler.open({
      description: 'Express Donation',
      zipCode: true,
      name: 'Space Foundation',
      panelLabel: 'Donate!',
      amount: amt,
      email: email
    });

  });

  // Close Checkout on page navigation:
  window.addEventListener('popstate', function() {
    stripeHandler.close();
  });

});
  
</script>

</body>
</html>
```

As far as "kosher" goes, I think this works as the token is returned to the client before submitting the form usually (I think, fact checking...).

Thanks again!
