### ISSUE TITLE
AWS API Gateway Integration?

### ISSUE THREAD

**Issue by yoolbinum** [TaylorBriggs/stripe-lambda#3]
Hi Taylor:
I was able to deploy your code on lambda and test event went fine. But now I tried to trigger lambda function with AWS API Gateway but I keep getting this.

{"message":"Missing Authentication Token"}

Could you briefly describe how you configure API Gateway? Thanks

**Comment by TaylorBriggs** [comment]
Hello,

The [AWS docs](http://docs.aws.amazon.com/apigateway/latest/developerguide/getting-started.html) are pretty extensive on this topic, so I definitely recommend reading through those.

The error message you're getting back seems to be related to this issue also: http://docs.aws.amazon.com/apigateway/latest/developerguide/amazon-api-gateway-using-stage-variables.html

It's been a while since I've set this all up so I can't remember all of the exact steps, but the AWS docs should include everything you need to get it set up and working.

**Comment by peoplemerge** [comment]
@uyb6711 see my comments elaborating my setup at #1

**Comment by TaylorBriggs** [comment]
Thanks for helping each other out here. I'm going to close this for now as the AWS config is a bit outside the scope of this repo.
